package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 18 16:13:02 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SourceVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SourceVVOImpl() {
    }
}
