package model.am;

import model.am.common.VigilanceAM;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 23 10:53:17 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VigilanceAMImpl extends ApplicationModuleImpl implements VigilanceAM {
    /**
     * This is the default constructor (do not remove).
     */
    public VigilanceAMImpl() {
    }

    /**
     * Container's getter for BrmastVO1.
     * @return BrmastVO1
     */
    public ViewObjectImpl getBrmastVO1() {
        return (ViewObjectImpl)findViewObject("BrmastVO1");
    }

    /**
     * Container's getter for BranchTransVO.
     * @return BranchTransVO
     */
    public ViewObjectImpl getBranchTransVO() {
        return (ViewObjectImpl)findViewObject("BranchTransVO");
    }

    /**
     * Container's getter for AttemptedTheftDetailsVO.
     * @return AttemptedTheftDetailsVO
     */
    public ViewObjectImpl getAttemptedTheftDetailsVO() {
        return (ViewObjectImpl)findViewObject("AttemptedTheftDetailsVO");
    }

    /**
     * Container's getter for CaseRegistrationVO.
     * @return CaseRegistrationVO
     */
    public ViewObjectImpl getCaseRegistrationVO() {
        return (ViewObjectImpl)findViewObject("CaseRegistrationVO");
    }

    /**
     * Container's getter for CbiDetailsVO.
     * @return CbiDetailsVO
     */
    public ViewObjectImpl getCbiDetailsVO() {
        return (ViewObjectImpl)findViewObject("CbiDetailsVO");
    }

    /**
     * Container's getter for ComplaintDetailsVO.
     * @return ComplaintDetailsVO
     */
    public ViewObjectImpl getComplaintDetailsVO() {
        return (ViewObjectImpl)findViewObject("ComplaintDetailsVO");
    }

    /**
     * Container's getter for CteDetailsVO.
     * @return CteDetailsVO
     */
    public ViewObjectImpl getCteDetailsVO() {
        return (ViewObjectImpl)findViewObject("CteDetailsVO");
    }

    /**
     * Container's getter for FraudDetailsVO.
     * @return FraudDetailsVO
     */
    public ViewObjectImpl getFraudDetailsVO() {
        return (ViewObjectImpl)findViewObject("FraudDetailsVO");
    }

    /**
     * Container's getter for MiscDetailsVO.
     * @return MiscDetailsVO
     */
    public ViewObjectImpl getMiscDetailsVO() {
        return (ViewObjectImpl)findViewObject("MiscDetailsVO");
    }

    /**
     * Container's getter for RiskFocussedDetailsVO.
     * @return RiskFocussedDetailsVO
     */
    public ViewObjectImpl getRiskFocussedDetailsVO() {
        return (ViewObjectImpl)findViewObject("RiskFocussedDetailsVO");
    }

    /**
     * Container's getter for RtiDetailsVO.
     * @return RtiDetailsVO
     */
    public ViewObjectImpl getRtiDetailsVO() {
        return (ViewObjectImpl)findViewObject("RtiDetailsVO");
    }

    /**
     * Container's getter for SmiDetailsVO.
     * @return SmiDetailsVO
     */
    public ViewObjectImpl getSmiDetailsVO() {
        return (ViewObjectImpl)findViewObject("SmiDetailsVO");
    }

    /**
     * Container's getter for StaffAccountabilityDetailsVO.
     * @return StaffAccountabilityDetailsVO
     */
    public ViewObjectImpl getStaffAccountabilityDetailsVO() {
        return (ViewObjectImpl)findViewObject("StaffAccountabilityDetailsVO");
    }
    
    public void initPage(){
        getComplaintDetailsVO().executeEmptyRowSet();
        getFraudDetailsVO().executeEmptyRowSet();
        getStaffAccountabilityDetailsVO().executeEmptyRowSet();
        getRiskFocussedDetailsVO().executeEmptyRowSet();
    }
}
