package model.am.client;

import model.am.common.VigilanceAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 23 10:55:20 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VigilanceAMClient extends ApplicationModuleImpl implements VigilanceAM {
    /**
     * This is the default constructor (do not remove).
     */
    public VigilanceAMClient() {
    }

    public void initPage() {
        Object _ret = this.riInvokeExportedMethod(this,"initPage",null,null);
        return;
    }
}
