package model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 23 10:55:20 IST 2016
// ---------------------------------------------------------------------
public interface VigilanceAM extends ApplicationModule {
    void initPage();
}
